import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
  buildRegistry,
  parseRecipeFile,
  renderSkillMarkdown,
  type Recipe,
  type Registry,
} from "@shortwind/core";
import { resolveHome, type ResolvedHome } from "../../home.js";

/**
 * `skill` — emit the Shortwind Cloud SKILL.md (PRD §7.3, the "works-today"
 * discovery layer).
 *
 * An agent that has the CLI on PATH can run `shortwind cloud skill` to learn,
 * in one document:
 *   1. the cloud VERBS it can call (find / publish / update / get / delete /
 *      visibility / bind-domain) — so it never invents an endpoint, and
 *   2. the account's CURRENT recipe palette (§5.7 discovery) — so it composes
 *      HTML from recipes that actually exist before publishing, instead of
 *      writing `@card` blind and shipping a raw token.
 *
 * The palette section reuses `@shortwind/core`'s {@link renderSkillMarkdown}
 * over the active home's `recipes/` (the same generator the local CLI uses), so
 * the cloud SKILL never drifts from the local one. The cloud-verbs section is
 * PREPENDED.
 *
 * Rendering is split into a PURE core ({@link renderCloudSkill}, takes a
 * {@link Registry}) and an IO shell ({@link runSkill}, reads the home palette
 * and writes/prints), so the golden test drives a fixed palette with no disk.
 */

export interface SkillOptions {
  /** Write the rendered SKILL.md to this path instead of stdout. */
  out?: string;
}

// ---------------------------------------------------------------------------
// The cloud-verbs section — a stable, hand-authored contract block. This is the
// half an agent reads to know WHICH verbs exist; the palette half (below) tells
// it which recipes exist.
// ---------------------------------------------------------------------------

const SKILL_NAME = "shortwind-cloud";
const SKILL_DESCRIPTION =
  "Publish, find, update, and manage agent-authored HTML pages on Shortwind Cloud. Use these verbs to ship a page to a real URL and to discover the account's current recipe palette before composing HTML.";

/** Each cloud verb: the CLI invocation, the REST route, and a one-line intent. */
interface VerbDoc {
  usage: string;
  route: string;
  blurb: string;
}

const VERB_DOCS: VerbDoc[] = [
  {
    usage: "shortwind cloud find [--q <text>] [--domain <d>] [--tag <t>] [--json]",
    route: "GET /v1/pages",
    blurb: "Locate existing pages — the account is the only memory; find before you publish.",
  },
  {
    usage: "shortwind cloud publish <file.html> [--bundle] [--domain <slug>] [--tag <t>] [--visibility <level>] [--json]",
    route: "POST /v1/pages",
    blurb: "Create a NEW page from an HTML file — or, with --bundle, publish <file>'s whole directory as ONE linked multi-page site (see Multi-page sites below). A slug conflict returns the existing id — use update.",
  },
  {
    usage: "shortwind cloud update <id> <file.html> [--json]",
    route: "PATCH /v1/pages/{id}",
    blurb: "Republish HTML to the SAME URL as a new version. Use the id find/publish returned.",
  },
  {
    usage: "shortwind cloud get <id> [--json]",
    route: "GET /v1/pages/{id}",
    blurb: "Fetch a page's metadata + version history to confirm before acting.",
  },
  {
    usage: "shortwind cloud delete <id> [-y|--yes] [--json]",
    route: "DELETE /v1/pages/{id}",
    blurb: "Tombstone a page. Prompts unless --yes; pass --yes for unattended agents.",
  },
  {
    usage: "shortwind cloud visibility <id> <public|unlisted|private> [--json]",
    route: "PATCH /v1/pages/{id}/visibility",
    blurb: "Set the access level. Validated client-side against the three known levels.",
  },
  {
    usage: "shortwind cloud bind-domain <id> <hostname> [--json]",
    route: "POST /v1/pages/{id}/domain",
    blurb: "Bind a custom hostname (requires the domains:bind scope — re-login with --scope).",
  },
];

/**
 * Render the SKILL.md for the cloud CLI: frontmatter + cloud-verbs section +
 * the account's recipe palette (via core's {@link renderSkillMarkdown}, with
 * its own frontmatter stripped so this document has exactly one). Pure — the
 * same `registry` always yields the same bytes (golden-stable).
 */
export function renderCloudSkill(registry: Registry): string {
  const parts: string[] = [];
  parts.push("---");
  parts.push(`name: ${SKILL_NAME}`);
  parts.push(`description: ${SKILL_DESCRIPTION}`);
  parts.push("---");
  parts.push("");
  parts.push(
    "<!-- AUTO-GENERATED by `shortwind cloud skill`. The verbs are fixed; the recipe palette reflects this account's current vocabulary. -->",
  );
  parts.push("");
  parts.push("# Shortwind Cloud");
  parts.push("");
  parts.push(
    "Shortwind Cloud hosts agent-authored HTML at a real URL. The CLI is stateless: it never remembers a page id — `find` an existing page, then `publish` a new one or `update` the id you found. The account is the only memory.",
  );
  parts.push("");
  parts.push("## Verbs");
  parts.push("");
  parts.push(
    "Every verb authenticates with the active account's token (run `shortwind cloud login` once). Add `--json` for machine-readable output.",
  );
  parts.push("");
  for (const v of VERB_DOCS) {
    parts.push(`- \`${v.usage}\``);
    parts.push(`  - ${v.route} — ${v.blurb}`);
  }
  parts.push("");
  parts.push("## Multi-page sites");
  parts.push("");
  parts.push(
    "To publish a SITE of multiple linked HTML pages (not a single page), pass `--bundle` to `publish`:",
  );
  parts.push("");
  parts.push(
    "- `shortwind cloud publish index.html --bundle` deploys the entry file's WHOLE directory of `.html` files as one linked unit (POST /v1/bundles). The entry (`index.html`) is the page the slug/subdomain routes to.",
  );
  parts.push(
    "- Each file serves at its AUTHORED path under the same subdomain: `index.html` → `https://<slug>.shortwind.app/`, `docs/guide.html` → `https://<slug>.shortwind.app/docs/guide.html`.",
  );
  parts.push(
    "- Relative links between pages work as authored — there is NO link rewriting. Write `<a href=\"docs/guide.html\">` normally.",
  );
  parts.push(
    "- The whole bundle is one unit for versioning, visibility, and takedown (it inherits the entry page's lifecycle).",
  );
  parts.push("");
  parts.push("## Recipe palette");
  parts.push("");
  parts.push(
    "These are the recipes installed in THIS account's home. Compose HTML from these names before publishing — a recipe the account doesn't ship expands to nothing and ships as raw text.",
  );
  parts.push("");
  parts.push(stripFrontmatter(renderSkillMarkdown(registry)));

  return parts.join("\n");
}

/**
 * Drop the leading `---`…`---` YAML frontmatter block (and the blank line after
 * it) from a rendered SKILL.md, so core's palette output embeds under the cloud
 * document's single frontmatter instead of carrying its own.
 */
function stripFrontmatter(markdown: string): string {
  if (!markdown.startsWith("---\n")) return markdown;
  const end = markdown.indexOf("\n---\n", 4);
  if (end === -1) return markdown;
  // Skip past the closing fence and any single trailing blank line.
  let rest = markdown.slice(end + "\n---\n".length);
  if (rest.startsWith("\n")) rest = rest.slice(1);
  return rest;
}

// ---------------------------------------------------------------------------
// IO shell — load the home palette into a Registry, then render + emit.
// ---------------------------------------------------------------------------

/**
 * Load the recipe families from a home's `recipes/` dir into a {@link Registry}
 * (leniently — a family that fails to resolve is skipped, never throws, so the
 * skill still advertises everything that DID parse). Mirrors the local CLI's
 * `loadInstalledRegistry`, kept local here because `@shortwind/cli` is not a
 * cloud dependency.
 */
export function loadHomePalette(recipesDir: string): Registry {
  if (!existsSync(recipesDir)) return { flattened: {}, families: {} };
  const allRecipes: Recipe[] = [];
  const guidance: Record<string, string> = {};
  const families = readdirSync(recipesDir)
    .filter((f) => f.endsWith(".css"))
    .map((f) => f.slice(0, -".css".length))
    .sort();
  for (const family of families) {
    const source = readFileSync(path.join(recipesDir, `${family}.css`), "utf8");
    const parsed = parseRecipeFile(source, `${family}.css`);
    if (!parsed.ok) continue;
    allRecipes.push(...parsed.value.recipes);
    if (parsed.value.guidance) guidance[family] = parsed.value.guidance;
  }
  const built = buildRegistry(allRecipes, { guidance });
  if (built.ok) return built.value;
  // Degrade to a name-only registry so the palette still lists the recipes.
  return { flattened: Object.fromEntries(allRecipes.map((r) => [r.name, []])), families: {} };
}

/**
 * Run `skill`: resolve the active home, load its palette, render the cloud
 * SKILL.md, and either return it (stdout) or write it to `--out`. Returns the
 * rendered markdown so cli.ts can print it and tests can assert it.
 */
export function runSkill(opts: SkillOptions, home: ResolvedHome = resolveHome()): string {
  const registry = loadHomePalette(home.recipesDir);
  const markdown = renderCloudSkill(registry);
  if (opts.out) {
    mkdirSync(path.dirname(path.resolve(opts.out)), { recursive: true });
    writeFileSync(path.resolve(opts.out), markdown.endsWith("\n") ? markdown : markdown + "\n");
  }
  return markdown;
}
