import type { Recipe, Registry } from "./types.js";

export type SkillRenderOptions = {
  name?: string;
  description?: string;
  order?: string[];
  verbose?: boolean;
  wrapAt?: number;
  // Which Shortwind adapter the project uses — selects the right package and
  // registry-loading idiom in the dynamic-classes escape-hatch and strict-mode
  // snippets (#81). Omitted: generic snippets naming all three.
  adapter?: SkillAdapter;
};

export type SkillAdapter = "vite" | "next" | "astro";

const DEFAULT_NAME = "shortwind";
const DEFAULT_DESCRIPTION =
  "Token-efficient class layer for Tailwind. Use @recipe shortcuts to compose pre-built class clusters when generating HTML, mockups, dashboards, PR write-ups, or any UI output.";
const DEFAULT_WRAP_AT = 80;

export function renderSkillMarkdown(registry: Registry, options: SkillRenderOptions = {}): string {
  const name = options.name ?? DEFAULT_NAME;
  const description = options.description ?? DEFAULT_DESCRIPTION;
  const verbose = options.verbose ?? false;
  const wrapAt = options.wrapAt ?? DEFAULT_WRAP_AT;

  const families = orderFamilies(registry, options.order);

  const parts: string[] = [];
  parts.push("---");
  parts.push(`name: ${name}`);
  parts.push(`description: ${description}`);
  parts.push("---");
  parts.push("");
  parts.push("<!-- AUTO-GENERATED by shortwind. Edit recipes in ./recipes/*.css instead. -->");
  parts.push("");
  parts.push("# Shortwind");
  parts.push("");
  parts.push(
    "Shortwind defines named recipes like `@card` that expand into Tailwind class strings at build time. Use them wherever you write `class=` or `className=`. The last-wins conflict resolver handles overlap with raw utilities.",
  );
  parts.push("");
  parts.push("## When to use");
  parts.push("");
  parts.push("- Generating HTML, JSX/TSX, or mockup output.");
  parts.push("- Producing UI snippets where short, predictable class strings matter.");
  parts.push("- Any time a project already ships with a Shortwind catalog.");
  parts.push("");
  parts.push("## How to use");
  parts.push("");
  parts.push("1. Reference recipes by name with the `@` prefix: `class=\"@card-elevated p-6\"`.");
  parts.push("2. Names follow `@<family>[-<intent>][-<size>]` — never invent new ones; use what's listed below.");
  parts.push("3. Recipes already include hover, focus, and dark-mode variants where relevant. Don't restate them.");
  parts.push("4. Append raw Tailwind utilities to override. Last position wins on conflicts.");
  parts.push("");

  parts.push("## Dynamic classes");
  parts.push("");
  parts.push(
    "The rule: the recipe text must appear as a **literal string the build can see** in a `class`/`className` attribute. What counts as visible depends on the file type:",
  );
  parts.push("");
  parts.push(
    "- **JSX/TSX (`.tsx`, `.jsx`, `.mdx`):** literal strings inside a `className={…}` expression DO expand — including both branches of a ternary, strings inside `clsx(...)`-style arguments, and the static parts of template literals.",
  );
  parts.push(
    "- **HTML-shaped templates (`.astro`, `.vue`, `.svelte`, `.html`):** only plain `class=\"...\"` attribute strings expand. A `class={…}` JS expression and Astro's `class:list={…}` do NOT — the same ternary that works in a `.tsx` island ships dead tokens here.",
  );
  parts.push(
    "- **All modes — the silent failure:** a recipe that reaches the attribute *indirectly* — assigned to a variable first, passed as a component prop, looked up from an object, or built by string concatenation — is never expanded, and the build cannot warn about it.",
  );
  parts.push("");
  // Examples are built from recipes that exist in THIS registry — a SKILL.md
  // generated for the starter preset must never demonstrate with a recipe the
  // install doesn't ship (#80: the old hardcoded @badge-success/@tab examples
  // referenced families absent from starter).
  const ex = exampleRecipes(registry);
  const commented = (code: string, comment: string): string =>
    code + " ".repeat(Math.max(1, 56 - code.length)) + comment;
  parts.push("```tsx");
  parts.push(commented(`<div className="@${ex.single} p-6">`, "// expands"));
  parts.push(
    commented(`<a className={active ? "@${ex.pairOn}" : "@${ex.pairOff}"}>`, "// expands (JSX only)"),
  );
  parts.push(`const cfg = { recipe: "@${ex.dynamic}" };`);
  parts.push(commented(`<span className={cfg.recipe}>`, "// does NOT expand — silent"));
  parts.push("```");
  parts.push("");
  parts.push(
    "Write static class lists literally. For a genuine runtime choice between recipes, use the escape hatch below — don't route around it with raw Tailwind.",
  );
  parts.push("");
  parts.push(...renderEscapeHatch(options.adapter, ex));
  parts.push(...renderStrictMode(options.adapter));

  if (families.length === 0) {
    parts.push("## Available recipes");
    parts.push("");
    parts.push("_No families installed yet. Run `shortwind add <family>` to install one._");
    parts.push("");
    return parts.join("\n");
  }

  parts.push("## Available recipes");
  parts.push("");
  // Only emit the selection hint when at least one family ships guidance —
  // otherwise it points at a convention the catalog doesn't use.
  const hasGuidance = families.some((f) => registry.guidance?.[f]);
  if (hasGuidance) {
    parts.push(
      "Each family below opens with a one-line guide on when to reach for which recipe. Read it before picking — it calls out easy-to-confuse neighbours.",
    );
    parts.push("");
  }
  for (const family of families) {
    const recipes = registry.families[family] ?? [];
    parts.push(`### ${capitalize(family)} recipes`);
    parts.push("");
    const guidance = registry.guidance?.[family];
    if (guidance) {
      parts.push(`> ${guidance}`);
      parts.push("");
    }
    parts.push(...renderFamily(recipes, registry, verbose, wrapAt));
    parts.push("");
  }

  return parts.join("\n");
}

// The worked rc()/expandClassList example, offered at the point of pain (#81
// — every beta.11 agent wished for exactly this and never found it). The
// registry import differs per adapter: Vite-based adapters serve the
// bundle-clean `virtual:shortwind/registry` module; in Next the registry
// loads server-side from recipes/ on disk.
function renderEscapeHatch(adapter: SkillAdapter | undefined, ex: ExampleRecipes): string[] {
  const out: string[] = [];
  out.push("### Runtime escape hatch: `rc()` / `expandClassList`");
  out.push("");
  out.push(
    "Expand the recipe at RUNTIME and bind the resulting plain-Tailwind string:",
  );
  out.push("");
  if (adapter === "next") {
    out.push("```ts");
    out.push("// lib/rc.ts — server-side (the registry reads recipes/ from disk)");
    out.push(`import { expandClassList, loadRegistryFromDir } from "@shortwind/next";`);
    out.push(`const registry = loadRegistryFromDir("recipes");`);
    out.push("export const rc = (classList: string): string => expandClassList(classList, registry, true);");
    out.push("```");
  } else {
    const pkg = adapter === "astro" ? "@shortwind/astro" : "@shortwind/vite";
    out.push("```ts");
    out.push("// src/lib/rc.ts");
    out.push(`import { expandClassList } from "${pkg}";`);
    out.push(`import registry from "virtual:shortwind/registry";`);
    out.push("export const rc = (classList: string): string => expandClassList(classList, registry, true);");
    out.push("```");
  }
  out.push("");
  out.push("```tsx");
  out.push(`<span className={ok ? rc("@${ex.pairOn}") : rc("@${ex.pairOff}")}>`);
  out.push("```");
  out.push("");
  out.push("Full guide: https://shortwind.dev/docs/dynamic-classes");
  out.push("");
  return out;
}

// Copy-pasteable strict wiring per adapter (#81): opt-in build gate that
// fails on any leaked @recipe token instead of shipping unstyled UI.
function renderStrictMode(adapter: SkillAdapter | undefined): string[] {
  const snippets: Record<SkillAdapter, string[]> = {
    vite: [
      "// vite.config.ts",
      `import { shortwind } from "@shortwind/vite";`,
      "export default defineConfig({ plugins: [shortwind({ strict: true }), tailwindcss()] });",
    ],
    next: [
      "// next.config.ts",
      `import { withShortwind } from "@shortwind/next";`,
      "export default withShortwind({ strict: true })(nextConfig);",
    ],
    astro: [
      "// astro.config.mjs",
      `import shortwind from "@shortwind/astro";`,
      "export default defineConfig({ integrations: [shortwind({ strict: true })] });",
    ],
  };
  const out: string[] = [];
  out.push("### Catch silent leaks: turn on `strict`");
  out.push("");
  out.push(
    "A leaked `@token` ships as raw text behind a green build. `strict: true` fails the build on any residual recipe token instead (the `rc()` pattern above stays exempt):",
  );
  out.push("");
  for (const a of adapter ? [adapter] : (["vite", "next", "astro"] as const)) {
    out.push("```ts");
    out.push(...snippets[a]);
    out.push("```");
  }
  out.push("");
  out.push(
    "`strict` lives inside the adapter — if the adapter was never wired, it cannot fire and the build ships raw `@tokens` silently. After any production build, run `npx shortwind doctor`: it scans the emitted output (`.next/`, `dist/`, …) for raw recipe tokens and tells you whether no transform ran at all (wiring problem) or the transform ran and specific tokens leaked.",
  );
  out.push("");
  return out;
}

type ExampleRecipes = { single: string; pairOff: string; pairOn: string; dynamic: string };

// Pick recipes from the registry for the dynamic-classes examples, preferring
// the familiar catalog names when they happen to be installed. An empty
// registry keeps generic placeholders (the recipes section below says nothing
// is installed yet, so nothing can be copy-pasted either way).
function exampleRecipes(registry: Registry): ExampleRecipes {
  const names = Object.keys(registry.flattened).sort();
  if (names.length === 0) {
    return { single: "card-elevated", pairOff: "tab", pairOn: "tab-active", dynamic: "badge-success" };
  }
  const has = (n: string): boolean => Object.hasOwn(registry.flattened, n);
  const firstDashed = names.find((n) => n.includes("-")) ?? names[0]!;
  const single = has("card-elevated") ? "card-elevated" : firstDashed;
  // A base/variant pair reads best in the ternary (`tab` vs `tab-active`);
  // fall back to any two distinct recipes.
  let pairOff = names[0]!;
  let pairOn = names[1] ?? names[0]!;
  if (has("tab") && has("tab-active")) {
    [pairOff, pairOn] = ["tab", "tab-active"];
  } else {
    const base = names.find((n) => names.includes(`${n}-active`));
    if (base) [pairOff, pairOn] = [base, `${base}-active`];
  }
  const dynamic = has("badge-success")
    ? "badge-success"
    : ([...names].reverse().find((n) => n.includes("-")) ?? single);
  return { single, pairOff, pairOn, dynamic };
}

function orderFamilies(registry: Registry, override: string[] | undefined): string[] {
  const all = Object.keys(registry.families);
  if (!override || override.length === 0) return all;
  const set = new Set(all);
  const out: string[] = [];
  for (const name of override) {
    if (set.has(name)) {
      out.push(name);
      set.delete(name);
    }
  }
  for (const name of all) if (set.has(name)) out.push(name);
  return out;
}

function renderFamily(
  recipes: Recipe[],
  registry: Registry,
  verbose: boolean,
  wrapAt: number,
): string[] {
  if (recipes.length === 0) return [];
  const maxName = Math.max(...recipes.map((r) => r.name.length));
  const nameCol = maxName + 4;
  const out: string[] = [];
  for (const recipe of recipes) {
    if (verbose && recipe.description) out.push(`  # ${recipe.description}`);
    // Object.hasOwn + array check: on a registry deserialized from JSON
    // (plain prototype), a recipe named `constructor`/`toString` would otherwise
    // resolve an inherited member and throw `.length`/`.join` on a non-array.
    const expanded = Object.hasOwn(registry.flattened, recipe.name)
      ? registry.flattened[recipe.name]
      : undefined;
    const tokens =
      Array.isArray(expanded) && expanded.length > 0 ? expanded.join(" ") : "(no tokens)";
    const prefix = `  @${recipe.name}${" ".repeat(nameCol - recipe.name.length - 1)}`;
    out.push(...wrapTokens(prefix, tokens, wrapAt));
  }
  return out;
}

function wrapTokens(prefix: string, tokens: string, wrapAt: number): string[] {
  const hanging = " ".repeat(prefix.length);
  const words = tokens.split(/\s+/).filter(Boolean);
  if (words.length === 0) return [prefix.trimEnd()];
  const lines: string[] = [];
  let current = prefix;
  let atLineStart = true;
  for (const word of words) {
    const candidate = atLineStart ? current + word : current + " " + word;
    if (candidate.length > wrapAt && !atLineStart) {
      lines.push(current);
      current = hanging + word;
      atLineStart = false;
      continue;
    }
    current = candidate;
    atLineStart = false;
  }
  if (current.length > 0) lines.push(current);
  return lines;
}

function capitalize(s: string): string {
  if (s.length === 0) return s;
  return (s[0] ?? "").toUpperCase() + s.slice(1);
}
