import type { Recipe, Registry } from "./types.js";

export type SkillRenderOptions = {
  name?: string;
  description?: string;
  order?: string[];
  verbose?: boolean;
  wrapAt?: number;
};

const DEFAULT_NAME = "shortwind";
const DEFAULT_DESCRIPTION =
  "Token-efficient class layer for Tailwind. Use @recipe shortcuts to compose pre-built class clusters when generating HTML, mockups, dashboards, PR write-ups, or any UI output.";
const DEFAULT_WRAP_AT = 80;

export function renderSkillMarkdown(registry: Registry, options: SkillRenderOptions = {}): string {
  const name = options.name ?? DEFAULT_NAME;
  const description = options.description ?? DEFAULT_DESCRIPTION;
  const verbose = options.verbose ?? false;
  const wrapAt = options.wrapAt ?? DEFAULT_WRAP_AT;

  const families = orderFamilies(registry, options.order);

  const parts: string[] = [];
  parts.push("---");
  parts.push(`name: ${name}`);
  parts.push(`description: ${description}`);
  parts.push("---");
  parts.push("");
  parts.push("<!-- AUTO-GENERATED by shortwind. Edit recipes in ./recipes/*.css instead. -->");
  parts.push("");
  parts.push("# Shortwind");
  parts.push("");
  parts.push(
    "Shortwind defines named recipes like `@card` that expand into Tailwind class strings at build time. Use them wherever you write `class=` or `className=`. The last-wins conflict resolver handles overlap with raw utilities.",
  );
  parts.push("");
  parts.push("## When to use");
  parts.push("");
  parts.push("- Generating HTML, JSX/TSX, or mockup output.");
  parts.push("- Producing UI snippets where short, predictable class strings matter.");
  parts.push("- Any time a project already ships with a Shortwind catalog.");
  parts.push("");
  parts.push("## How to use");
  parts.push("");
  parts.push("1. Reference recipes by name with the `@` prefix: `class=\"@card-elevated p-6\"`.");
  parts.push("2. Names follow `@<family>[-<intent>][-<size>]` — never invent new ones; use what's listed below.");
  parts.push("3. Recipes already include hover, focus, and dark-mode variants where relevant. Don't restate them.");
  parts.push("4. Append raw Tailwind utilities to override. Last position wins on conflicts.");
  parts.push("");

  parts.push("## Dynamic classes");
  parts.push("");
  parts.push(
    "Recipes expand only inside **literal** `class=\"...\"` / `className=\"...\"` strings. A recipe placed in a JS expression — a ternary, a template literal, an Astro `class:list`, or a value passed as a component prop — is not expanded and ships as a dead `@recipe` token, so the element renders unstyled. The build warns when it can see such a token; if the recipe reaches the attribute indirectly (via a variable or prop) it stays silent.",
  );
  parts.push("");
  parts.push("```");
  parts.push("<div class=\"@card-elevated p-6\">                 <!-- expands -->");
  parts.push("<a class={active ? \"@nav-link-active\" : \"@nav-link\"}>  <!-- does NOT expand -->");
  parts.push("```");
  parts.push("");
  parts.push(
    "Write static class lists literally. For a runtime choice between recipes, expand them at build time with `expandClassList` from `@shortwind/core` and bind the resulting Tailwind — full helper at https://shortwind.dev/docs/dynamic-classes.",
  );
  parts.push("");

  if (families.length === 0) {
    parts.push("## Available recipes");
    parts.push("");
    parts.push("_No families installed yet. Run `shortwind add <family>` to install one._");
    parts.push("");
    return parts.join("\n");
  }

  parts.push("## Available recipes");
  parts.push("");
  // Only emit the selection hint when at least one family ships guidance —
  // otherwise it points at a convention the catalog doesn't use.
  const hasGuidance = families.some((f) => registry.guidance?.[f]);
  if (hasGuidance) {
    parts.push(
      "Each family below opens with a one-line guide on when to reach for which recipe. Read it before picking — it calls out easy-to-confuse neighbours.",
    );
    parts.push("");
  }
  for (const family of families) {
    const recipes = registry.families[family] ?? [];
    parts.push(`### ${capitalize(family)} recipes`);
    parts.push("");
    const guidance = registry.guidance?.[family];
    if (guidance) {
      parts.push(`> ${guidance}`);
      parts.push("");
    }
    parts.push(...renderFamily(recipes, registry, verbose, wrapAt));
    parts.push("");
  }

  return parts.join("\n");
}

function orderFamilies(registry: Registry, override: string[] | undefined): string[] {
  const all = Object.keys(registry.families);
  if (!override || override.length === 0) return all;
  const set = new Set(all);
  const out: string[] = [];
  for (const name of override) {
    if (set.has(name)) {
      out.push(name);
      set.delete(name);
    }
  }
  for (const name of all) if (set.has(name)) out.push(name);
  return out;
}

function renderFamily(
  recipes: Recipe[],
  registry: Registry,
  verbose: boolean,
  wrapAt: number,
): string[] {
  if (recipes.length === 0) return [];
  const maxName = Math.max(...recipes.map((r) => r.name.length));
  const nameCol = maxName + 4;
  const out: string[] = [];
  for (const recipe of recipes) {
    if (verbose && recipe.description) out.push(`  # ${recipe.description}`);
    // Object.hasOwn + array check: on a registry deserialized from JSON
    // (plain prototype), a recipe named `constructor`/`toString` would otherwise
    // resolve an inherited member and throw `.length`/`.join` on a non-array.
    const expanded = Object.hasOwn(registry.flattened, recipe.name)
      ? registry.flattened[recipe.name]
      : undefined;
    const tokens =
      Array.isArray(expanded) && expanded.length > 0 ? expanded.join(" ") : "(no tokens)";
    const prefix = `  @${recipe.name}${" ".repeat(nameCol - recipe.name.length - 1)}`;
    out.push(...wrapTokens(prefix, tokens, wrapAt));
  }
  return out;
}

function wrapTokens(prefix: string, tokens: string, wrapAt: number): string[] {
  const hanging = " ".repeat(prefix.length);
  const words = tokens.split(/\s+/).filter(Boolean);
  if (words.length === 0) return [prefix.trimEnd()];
  const lines: string[] = [];
  let current = prefix;
  let atLineStart = true;
  for (const word of words) {
    const candidate = atLineStart ? current + word : current + " " + word;
    if (candidate.length > wrapAt && !atLineStart) {
      lines.push(current);
      current = hanging + word;
      atLineStart = false;
      continue;
    }
    current = candidate;
    atLineStart = false;
  }
  if (current.length > 0) lines.push(current);
  return lines;
}

function capitalize(s: string): string {
  if (s.length === 0) return s;
  return (s[0] ?? "").toUpperCase() + s.slice(1);
}
