import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildRegistry, parseRecipeFile } from "@shortwind/core";
import type { Recipe } from "@shortwind/core";

const here = path.dirname(fileURLToPath(import.meta.url));
const recipesDir = path.resolve(here, "..", "..", "registry", "recipes");
const outPath = path.resolve(here, "..", "src", "registry.generated.ts");

const files = readdirSync(recipesDir)
  .filter((f) => f.endsWith(".css"))
  .sort();

const recipes: Recipe[] = [];
for (const file of files) {
  const source = readFileSync(path.join(recipesDir, file), "utf8");
  const parsed = parseRecipeFile(source, file);
  if (!parsed.ok) {
    console.error(`Failed to parse ${file}:`, parsed.errors);
    process.exit(1);
  }
  recipes.push(...parsed.value.recipes);
}

const result = buildRegistry(recipes);
if (!result.ok) {
  console.error("Failed to build registry:", result.errors);
  process.exit(1);
}

const flattened = result.value.flattened;
const families = Object.fromEntries(
  Object.entries(result.value.families).map(([fam, recs]) => [
    fam,
    recs.map((r) => r.name),
  ]),
);

const body = `// AUTO-GENERATED by scripts/generate-registry.ts — do not edit by hand.
import type { Registry } from "@shortwind/core";

export const DEFAULT_REGISTRY: Registry = {
  flattened: ${JSON.stringify(flattened, null, 2)},
  families: ${JSON.stringify(
    Object.fromEntries(
      Object.entries(result.value.families).map(([fam, recs]) => [
        fam,
        recs.map((r) => ({
          name: r.name,
          description: r.description,
          tokens: r.tokens,
          references: r.references,
          sourceFile: r.sourceFile,
          sourceLine: r.sourceLine,
        })),
      ]),
    ),
    null,
    2,
  )},
};

export const DEFAULT_FAMILIES = ${JSON.stringify(Object.keys(families), null, 2)};
`;

writeFileSync(outPath, body);
console.log(
  `[runtime] wrote ${outPath} — ${Object.keys(flattened).length} recipes across ${Object.keys(families).length} families.`,
);
