export { init, DEFAULT_REGISTRY } from "./init.js";
export type { InitOptions, InitResult, InstallPackages } from "./init.js";
export { detectProject } from "./detect.js";
export type { PackageManager, Bundler, Framework, ProjectShape } from "./detect.js";
export { createRegistrySource, resolvePresetFamilies } from "./registry-source.js";
export type { RegistrySource, Presets } from "./registry-source.js";
export { add } from "./commands/add.js";
export type { AddOptions, AddResult } from "./commands/add.js";
export { remove } from "./commands/remove.js";
export type { RemoveOptions, RemoveResult } from "./commands/remove.js";
export { preset } from "./commands/preset.js";
export type { PresetOptions, PresetResult } from "./commands/preset.js";
export { ls, formatLsText } from "./commands/ls.js";
export type { LsOptions, LsResult } from "./commands/ls.js";
export { readLockfile, writeLockfile } from "./lockfile.js";
export type { Lockfile, LockEntry } from "./lockfile.js";
export { renameFamilyInSource } from "./project.js";
