#!/usr/bin/env node
// Embeds a snapshot of the built catalog into the CLI so `init`/`add` work with
// zero network — the default registry source reads this bundle. Re-run after
// the catalog changes:
//   pnpm --filter @shortwind/catalog build
//   pnpm --filter @shortwind/cli gen:catalog
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
// the @shortwind/catalog build output (sealed, versioned recipes + presets)
const DIST = path.resolve(here, "..", "..", "registry", "dist", "registry");
const OUT = path.resolve(here, "..", "src", "catalog.generated.ts");

if (!existsSync(DIST)) {
  console.error(
    `Catalog build not found at ${DIST}. Run \`pnpm --filter @shortwind/catalog build\` first.`,
  );
  process.exit(1);
}

const presets = readFileSync(path.join(DIST, "presets.json"), "utf8").trim();
const recipesDir = path.join(DIST, "recipes");
const families = readdirSync(recipesDir)
  .filter((f) => f.endsWith(".css"))
  .map((f) => f.replace(/\.css$/, ""))
  .sort();

const recipeEntries = families
  .map((fam) => `  ${JSON.stringify(fam)}: ${JSON.stringify(readFileSync(path.join(recipesDir, `${fam}.css`), "utf8"))},`)
  .join("\n");

const body = `// Generated by scripts/generate-catalog.ts — do not edit by hand.
// A snapshot of the @shortwind/catalog build, embedded so the CLI can resolve
// the default catalog with no network. Re-run \`pnpm --filter @shortwind/cli gen:catalog\`
// after the catalog changes.
import type { Presets } from "./registry-source.js";

export const CATALOG_PRESETS: Presets = ${presets};

export const CATALOG_FAMILIES: string[] = ${JSON.stringify(families)};

export const CATALOG_RECIPES: Record<string, string> = {
${recipeEntries}
};
`;

writeFileSync(OUT, body);
console.log(`Wrote ${OUT} (${families.length} families)`);
