#!/usr/bin/env node
/**
 * Embeds a snapshot of the standard @shortwind/catalog kit into the Convex
 * runtime so an account can be SEEDED with the full recipe palette on creation
 * (Convex has no filesystem at runtime). Mirrors the CLI's generate-catalog.ts,
 * but emits the SPLIT shape the palette store needs — { family, version,
 * bodySha, body } with the body stripped of its seal header (body-only is the
 * `recipeVersions` convention and is touch-inert, so re-feeding it never fires a
 * spurious recipe.edit; see convex/recipes.ts listRecipePalette).
 *
 * Re-run after the catalog changes:
 *   pnpm --filter @shortwind/catalog build
 *   pnpm --filter @shortwind/cloud gen:standard-kit
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// This script lives OUTSIDE `convex/` on purpose: Convex bundles everything
// under convex/ and would reject these node: imports. It only emits the pure
// data module `convex/lib/standard_kit.generated.ts` (which convex may bundle).
const here = path.dirname(fileURLToPath(import.meta.url));
const DIST = path.resolve(
  here,
  "..",
  "..",
  "..",
  "packages",
  "registry",
  "dist",
  "registry",
);
const OUT = path.resolve(here, "..", "convex", "lib", "standard_kit.generated.ts");

if (!existsSync(DIST)) {
  console.error(
    `Catalog build not found at ${DIST}. Run \`pnpm --filter @shortwind/catalog build\` first.`,
  );
  process.exit(1);
}

/** Parse the seal header (line 1) `/* shortwind: <family>@<version> sha:<sha> *​/`. */
const SEAL = /^\/\*\s*shortwind:\s*([a-z0-9-]+)@([0-9.]+)\s+sha:([0-9a-f]+)\s*\*\//;

const recipesDir = path.join(DIST, "recipes");
const families = readdirSync(recipesDir)
  .filter((f) => f.endsWith(".css"))
  .map((f) => f.replace(/\.css$/, ""))
  .sort();

const entries = families.map((family) => {
  const source = readFileSync(path.join(recipesDir, `${family}.css`), "utf8");
  const firstLine = source.slice(0, source.indexOf("\n"));
  const m = SEAL.exec(firstLine);
  if (!m) {
    console.error(`No seal header in ${family}.css (line 1: ${firstLine})`);
    process.exit(1);
  }
  const [, sealFamily, version, bodySha] = m;
  if (sealFamily !== family) {
    console.error(`Seal family "${sealFamily}" != file "${family}"`);
    process.exit(1);
  }
  // Body = everything after the seal line (matches core's bodyAfterHeader).
  const body = source.slice(source.indexOf("\n") + 1);
  return { family, version, bodySha, body };
});

const body = `// Generated by scripts/generate-standard-kit.ts — do not edit by hand.
// A snapshot of the @shortwind/catalog kit, embedded so a new Cloud account can
// be seeded with the full recipe palette server-side (Convex has no filesystem).
// Bodies are SEAL-STRIPPED (the recipeVersions body-only convention): touch-inert,
// so re-feeding them into a publish never fires a spurious recipe.edit.
// Re-run \`pnpm --filter @shortwind/cloud gen:standard-kit\` after the catalog changes.

export interface StandardRecipe {
  family: string;
  version: string;
  bodySha: string;
  body: string;
}

export const STANDARD_KIT: StandardRecipe[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(OUT, body);
console.log(`Wrote ${OUT} (${entries.length} families)`);
